DRV-262: Fix Repeat() signature
fauna/faunadb-go pull request #116
Opened 2020-09-21 13:12 UTC by trevorsibanda

- Make Number parameter optional

2020-09-21 16:31 UTC, faunaee commented
This change makes my example work. 👍

2020-09-22 16:40 UTC, erickpintor requested changes

2020-09-22 16:40 UTC, erickpintor commented on faunadb/functions_strings.go
> +func Repeat(str interface{}, number ...interface{}) Expr {
I think we should adhere to the standard optional interface. Something like:

```go
f.Repeat("foo", f.Number(3))
```
```

2020-09-29 16:37 UTC, faunaee commented
The update works too, although there is still a test that fails every time:

```
   --- FAIL: TestRunClientTests/TestEvalContainsFunctions (0.32s)
        client_test.go:1706: 
            	Error Trace:	client_test.go:1706
            	            				client_test.go:1715
            	            				client_test.go:1805
            	Error:      	Not equal: 
            	            	expected: true
            	            	actual  : false
            	Test:       	TestRunClientTests/TestEvalContainsFunctions
```

That test is likely unrelated to this PR's work, but it is something that should be fixed so that the tests pass and everyone can know which builds are good.

2020-09-30 18:22 UTC, erickpintor approved these changes
LGTM!

2020-10-05 17:05 UTC, merged