DRV-629: Improve function docblocks:
fauna/faunadb-go pull request #143
Opened 2021-04-15 23:29 UTC by faunaee

* Update links to documentation with current URLs.
* Add documentation links when they were missing.
* Make function, parameter, and return descriptions into full sentences.
* Make the presentation of parameters and return values more consistent.
* Add docblocks where they were missing.
* Fix typos, capitalization, and apply some wordsmithing.

2021-04-19 11:40 UTC, vadimLF submitted a review, later dismissed
LGTM.

2021-04-22 18:09 UTC, faunaee commented
@parkhomenko Please take a look when you get a chance!

2021-05-19 12:40 UTC, parkhomenko reviewed
looks great! there are only 2 small comments to check

2021-05-19 15:54 UTC, faunaee commented on faunadb/functions_auth.go
> +// See: https://docs.fauna.com/fauna/current/api/fql/functions/identity?lang=go
Good catch! Fixed.

2021-05-19 15:54 UTC, faunaee commented on faunadb/functions_sets.go
>  func Merge(merge interface{}, with interface{}, lambda ...OptionalParameter) Expr {
Yes! Thanks for catching this. Fixed.

2021-05-19 16:22 UTC, parkhomenko submitted a review, later dismissed

2021-06-15 14:23 UTC, rts-rob requested changes
I made it through 11 of 17 files - started into faunadb/functions_string.go

Some comments inline. Other requested changes:

1. For consistency's sake, there are a number of other instances of `FaunaDB` remaining. Suggest removing all of them that are not semantic, e.g., leave the driver header as is.
2. Please replace all non-semantic references to "Golang" or "Go lang" with "Go." Ref: https://golang.org/doc/faq#go_or_golang
3. There appears to be a capitalization inconsistency between *collection* and *Page* - suggest we select one style and keep it throughout.
4. In [functions_math.go](faunadb/functions_math.go) - proper names of the inverse trigonometric functions are *arccosine*, *arcsine*, *arctangent*, etc., with no spaces. Please revert.
5. In [functions_string.go](faunadb/functions_string.go) - please align boolean return explanations (examples given in individual comments) and the use of "bool" vs. "boolean" when describing return values.

2021-06-15 16:17 UTC, faunaee commented on faunadb/functions_basic.go
> +// expression. If no expressions are provided, do returns an error.
You are correct, it should be `Do`. I wrapped these lines, but did not otherwise pay attention to the content.

2021-06-15 16:34 UTC, faunaee commented on faunadb/functions_basic.go
>  //  Query - The lambda wrapped in a @query type.
`@query` is a wire protocol construct. `Query` is a function that wraps a `Lambda` in order to defer execution until the `Query` is evaluated (as in an index binding, or role predicate). It definitely needs to be exposed to users or they cannot create bindings/predicates with this driver.

I defer to the engineers to determine whether the return description is valid.

2021-06-15 16:35 UTC, faunaee commented on faunadb/functions_collections.go
> +// Page. It returns the result of each application on a collection of
A Page is a type that behaves like an Array. It contains an Array plus cursor information that would help navigate to previous or next Pages in a result set from Paginate.

2021-06-17 11:55 UTC, parkhomenko approved these changes

2022-02-11 16:25 UTC, closed without merging